package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/derKosi/Ohm/internal/model"
	"github.com/derKosi/Ohm/internal/platform"
)

// Generate creates a cleanup script from selected findings.
func Generate(result *model.ScanResult) (string, error) {
	osType := platform.Detect()
	ext := platform.ScriptExtension()
	timestamp := time.Now().Format("2006-01-02")
	filename := fmt.Sprintf("ohm-cleanup-%s%s", timestamp, ext)

	var sb strings.Builder

	// Header
	if osType == platform.OSWindows {
		sb.WriteString("# Ohm Cleanup Script (PowerShell)\n")
	} else {
		sb.WriteString("#!/usr/bin/env bash\n")
	}
	sb.WriteString(fmt.Sprintf("# Generated by Ohm on %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("# Platform: %s\n", result.Platform))
	sb.WriteString(fmt.Sprintf("# Hostname: %s\n", result.Hostname))
	sb.WriteString("#\n")
	sb.WriteString(fmt.Sprintf("# Total items: %d\n", result.SelectedCount()))
	sb.WriteString(fmt.Sprintf("# Total size to free: %s\n", model.FormatBytes(result.SelectedSize())))
	sb.WriteString("#\n")
	sb.WriteString("# ⚠️  REVIEW THIS SCRIPT BEFORE RUNNING!\n")
	sb.WriteString("# ⚠️  Some items may contain API keys or credentials.\n")
	sb.WriteString("# ⚠️  Ohm did NOT execute anything — you are in control.\n")
	sb.WriteString("#\n\n")

	if osType != platform.OSWindows {
		sb.WriteString("set -euo pipefail\n\n")
		sb.WriteString("echo \"Ohm Cleanup Script\"\n")
		sb.WriteString(fmt.Sprintf("echo \"Items to remove: %d\"\n", result.SelectedCount()))
		sb.WriteString(fmt.Sprintf("echo \"Estimated space to free: %s\"\n", model.FormatBytes(result.SelectedSize())))
		sb.WriteString("echo \"\"\n")
		sb.WriteString("read -p \"Continue? (y/N) \" confirm\n")
		sb.WriteString("if [ \"$confirm\" != \"y\" ] && [ \"$confirm\" != \"Y\" ]; then\n")
		sb.WriteString("    echo \"Aborted.\"\n")
		sb.WriteString("    exit 0\n")
		sb.WriteString("fi\n")
		sb.WriteString("echo \"\"\n\n")
	} else {
		sb.WriteString("$ErrorActionPreference = 'Stop'\n\n")
		sb.WriteString("Write-Host \"Ohm Cleanup Script\"\n")
		sb.WriteString(fmt.Sprintf("Write-Host \"Items to remove: %d\"\n", result.SelectedCount()))
		sb.WriteString(fmt.Sprintf("Write-Host \"Estimated space to free: %s\"\n", model.FormatBytes(result.SelectedSize())))
		sb.WriteString("Write-Host \"\"\n")
		sb.WriteString("$confirm = Read-Host \"Continue? (y/N)\"\n")
		sb.WriteString("if ($confirm -ne 'y' -and $confirm -ne 'Y') {\n")
		sb.WriteString("    Write-Host 'Aborted.'\n")
		sb.WriteString("    exit 0\n")
		sb.WriteString("}\n")
		sb.WriteString("Write-Host \"\"\n\n")
	}

	// Group by category
	groups := result.ByCategory()
	for _, group := range groups {
		var selected []model.Finding
		for _, fi := range group.FindingIdxs {
			f := result.Findings[fi]
			if f.Selected {
				selected = append(selected, f)
			}
		}
		if len(selected) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("# ─── %s ───\n\n", group.Category))

		for _, f := range selected {
			sb.WriteString(fmt.Sprintf("# %s\n", f.Name))
			sb.WriteString(fmt.Sprintf("# Size: %s\n", f.FormatSize()))
			if f.RiskLevel == model.RiskDanger {
				sb.WriteString("# ⚠️ WARNING: This may contain API keys or credentials!\n")
			} else if f.RiskLevel == model.RiskCaution {
				sb.WriteString("# ⚠️ Caution: Review before removing.\n")
			}

			// Get platform-specific command
			platformKey := osKey(osType)
			if cmd, ok := f.UninstallCmds[platformKey]; ok && cmd != "" {
				if strings.HasPrefix(cmd, "#") {
					sb.WriteString(cmd + "\n")
				} else {
					sb.WriteString(fmt.Sprintf("echo \"Removing %s...\"\n", f.Name))
					sb.WriteString(cmd + "\n")
				}
			}

			sb.WriteString("\n")
		}
	}

	// Footer
	sb.WriteString("# ─── Done ───\n")
	sb.WriteString(fmt.Sprintf("echo \"Cleanup script complete. %s freed (estimated).\"\n", model.FormatBytes(result.SelectedSize())))

	// Write to file
	if err := os.WriteFile(filename, []byte(sb.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write script: %w", err)
	}

	// Make executable on unix
	if osType != platform.OSWindows {
		os.Chmod(filename, 0755)
	}

	absPath, _ := filepath.Abs(filename)
	return absPath, nil
}

func osKey(osType platform.OS) string {
	switch osType {
	case platform.OSLinux:
		return "linux"
	case platform.OSMacOS:
		return "macos"
	case platform.OSWindows:
		return "windows"
	default:
		return "linux"
	}
}

func filterSelected(findings []model.Finding) []model.Finding {
	var result []model.Finding
	for _, f := range findings {
		if f.Selected {
			result = append(result, f)
		}
	}
	return result
}
